### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by rabbit-fgh** [zheng-peng-fei/NoiseDiffusion#1]
作者您好，请问可以提供openpose-sd21.ckpt模型文件吗？

**Comment by Tranquil1ty** [comment]
https://huggingface.co/thibaud/controlnet-sd21/tree/main

**Comment by rabbit-fgh** [comment]
感谢

> https://huggingface.co/thibaud/controlnet-sd21/tree/main

**Comment by rabbit-fgh** [comment]
作者您好，可以提供下训练脚本吗
