### ISSUE TITLE
Training of the LSUN dataset

### ISSUE THREAD

**Issue by wen2333333** [zheng-peng-fei/NoiseDiffusion#2]
Hello author, may I ask if there is a pre-trained model for the diffusion model training based on LSUN data, or did you train it by yourself? I didn't find it in the code, looking forward to your answer.

**Comment by Tranquil1ty** [comment]
No, I used the pre-trained model from [https://github.com/openai/consistency_models](url) :EDM on LSUN Bedroom-256 and EDM on LSUN Cat-256, and I'm currently organizing the code. The method is exactly the same as that in this repository, and I have listed the parameters in detail in the paper.

**Comment by wen2333333** [comment]
Ok, thanks for your help！
